Database basics PR
Javed-Shahbaz/Vet-Clinic-Database pull request #1
Opened 2023-06-20 21:58 UTC by Javed-Shahbaz

![image](https://github.com/Javed-Shahbaz/Vet-Clinic-Database/assets/76252961/b3b0cec8-ba0e-49df-bf74-4df126d8cf3f)
![image](https://github.com/Javed-Shahbaz/Vet-Clinic-Database/assets/76252961/7cd49f61-85c3-45ac-89af-65abeeaf1739)
![image](https://github.com/Javed-Shahbaz/Vet-Clinic-Database/assets/76252961/4a7fa0d8-f1f6-44aa-b281-9fe1af911bd2)
![image](https://github.com/Javed-Shahbaz/Vet-Clinic-Database/assets/76252961/29633c6e-7470-4486-b22a-9abac555fd03)
![image](https://github.com/Javed-Shahbaz/Vet-Clinic-Database/assets/76252961/c951f5be-7a60-4547-8f96-17863742d2ff)
![image](https://github.com/Javed-Shahbaz/Vet-Clinic-Database/assets/76252961/a6e6a257-4170-4be5-97bb-2150c18eb19e)
![image](https://github.com/Javed-Shahbaz/Vet-Clinic-Database/assets/76252961/a4217bb8-f6eb-4389-8c09-11e3087077ec)
![image](https://github.com/Javed-Shahbaz/Vet-Clinic-Database/assets/76252961/d28c8802-b22f-4c1a-8387-8c922d1d033f)
![image](https://github.com/Javed-Shahbaz/Vet-Clinic-Database/assets/76252961/f964e500-4638-4124-98d8-0b3ab6b8c34d)

2023-06-20 22:35 UTC, Lucas-Masaba requested changes
# Hello @Javed-Shahbaz  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Created the animals' table :cow: 
- All SQL is written in its respective files :file_cabinet: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 22:35 UTC, Lucas-Masaba commented on README.md
- [ ] Please customize your README to suit this current milestone as mentioned in the project requirements where it says please document your project in a professional way. When I look through your README, I see a lot of default text from the default README.

2023-06-20 22:35 UTC, Lucas-Masaba commented on README.md
> +
- [ ] In this project, you are using neither React as your client nor Express.js as your server. Please adjust this accordingly.

2023-06-20 22:35 UTC, Lucas-Masaba commented on README.md
> +## 🚀 Live Demo <a name="live-demo"></a>
- [ ] You do not have a live demo for this milestone so it would be best to leave a placeholder statement here mentioning that it is unavailable.

2023-06-20 22:35 UTC, Lucas-Masaba commented on README.md
> +## 💻 Getting Started <a name="getting-started"></a>
- [ ] The getting started section to the run tests section talks about Ruby on Rails but in this milestone, you are not using Ruby on Rails. Please adjust it accordingly.

2023-06-20 22:35 UTC, Lucas-Masaba commented on README.md
> +This project is [MIT](./LICENSE) licensed.
- [ ] This MIT license link leads to a 404 error page. Please fix the link.

2023-06-20 22:35 UTC, Lucas-Masaba commented on schema.sql
> +create table animals (id integer, name varchar(20), data_of_birth date,escape_attempts integer,neutered boolean,weight_kg decimal);
[OPTIONAL]
- I suggest you make the id column not null and autoincremented.
`id int NOT NULL IDENTITY(1,1)`
 And would also advise making it a primary key
`PRIMARY KEY (id)`

2023-06-22 18:27 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hi @Javed-Shahbaz 👋🏽 , 

Great work on making the changes requested by a previous reviewer 👏 
To highlight 👍🏽 
✔️ README is updated
✔️ SQL commands are in the correct files

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media.giphy.com/media/YT95XJOLvY1t2SJgpR/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 18:27 UTC, Ghiftee commented on README.md
> +  </ul>
- [ ] Your README still states `Reactjs` as your `Client` and `Expressjs` as your `server`. As the previous reviewer mentioned, these are not used in the project, please remove them.

2023-06-22 18:27 UTC, Ghiftee commented on README.md
> +This project is [MIT](./License.md) licensed.
- [ ] Your license is still broken. Please fix it.

2023-06-22 19:45 UTC, DuaneDave approved these changes
Hi @Javed-Shahbaz 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good job setting up the database

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 19:52 UTC, merged